language: python

source_key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBc1FTTG5pYjcyZVU3WlRlUXl0ZTcvR2dHVGpDKzlOaURJMGg1V1phVmVrd0libzJ4CnVzNmVsOHJYTlBrRi9rbXFsd0pkeGhGQ3V0NFVIeHF6dW01dW5zOWdHTHQ2WVRNeWU1NjVlRUVDeHBXM1ZWVnIKckQ4bUh2VGt3NHlVTDB0dnJYeVQvdjRNV1F0VWNDSWVGa3U5alZYTE4xTnZHR3hHeExrOFhFMlNWWDVvR3hEegpZVTZDenNhV1ArcnZ4d2owZHppQVhnSEg4NGxxSFBqK2RDdG5SSkdQWjdNanJ3Zm51NWF0d3I1V0I5VjhvUlM2CmVISVJLWTZ3Umc5L1RFOGgrQytJWDdJOGFMVEpoQWt6NjFWVjc2dk0yTUVya2NzQ1VhS05oclNVQlBpYnlaRSsKdEFRemNDN0tuamJBaGV4dWdvOXN4T0tZQS9XUHlOMTg0aVZUNFFJREFRQUJBb0lCQVFDYVMvRDdBTllFWHloLwptSWlRRnEzWVhFQXF4WmlkU1dBOVQvM2Vsa0JpNG9WeS8vVk1kSytPZGhOU0xFSUtIZUloVU1HMlZQTktlU3NtCjFacVZ4WTZNeFF2cFl2bFFZbFQ5cGlQYWF5aGxPcmtjRzZJSCtOOWNtbkFROTZkdTloMDVKbDdHSkdGVStHZzQKZWJTcUVJai8raWx4Wnp0dUdXc3lMSmd0aUx3bDRkN1VtcjhPTlRwWTNGNHM1TUVYTmwwWDdXRjV2THNUd3NyegpEZVU1ZEU5UkpDSHRYVWxwVjNaYW9PN2QrWWVnZ3JRNmc3L3llcG9remx1ajJRMjh3T1ovZkxVeEdLS25rNVU2CjZhcklhN2hvYVNQSGtvb1FhRkgxN2RtdWJyWHFqcUg1VGtIZ2U0d0xod25NSTVPbEptcXE0MGVWREpRNWp5dVIKN1RodnR1ZVZBb0dCQU5xY0U4aXdJb1hqQjlnTXpTdHpiTU9VaHJaZlUzb1ZXU1pnRXBLTjJnNi9NanV6eER1Wgo2MEYvTmp5Y05yL0ZjQlZwVzJxUmdyMlhzMFlWVnFiZ2ZPak54LzN0cnpSRFpJVlFVRzVJeEJUY1UveHhOQ1FUCnUyNW5lMXdpalIrWUoyYUJzZmdFc00xa0pDRXQraVdycmxaMVNxYkZGWlprVnNZYzNZVFIyaGYzQW9HQkFNOUwKV09Bcnk0emJ6QXhQTHdDZnZoclY4bitvSnkreFJINjBjSno1VTFHUmZQRzVTWnh5Y2xTaldvR2pVMjRCMm42UQpsZTNzbU01RXgzdm9xcit2U1NyaHRmTG1FbW5CRXBBWXlOYlZrV1g3MlZ5T25rbnN5UnNxckRQZ2pBMDhNakFQCmFQUHYzWEQ2RWlQT2h6aWZGbm1HZ1JQWlFFYVVCVWdEKy9GdFR1em5Bb0dBYUFyMlk0Sm91OTRFZ3EvOUNkd0MKZk1iNG9sMldKamw0MTRuTDdSSTBJT2FnYXNldzhramNMYXowekQzdzFLNk1ITFNxL0hwS2hoOW9CRWZ0bUxpbwoya2Z1RWcySVlGQmV6QkFnWjR5Y1BlMXF6MisxU0NKWUIwQ2E5b3UvTExWR3MwT3d4d0M4Z05SVFdiTS9KYVNpCjhhVWJKV29SVHlWc0l4ZmoyZTNpWlpzQ2dZRUFybzZoV2F3bmJRY05qWFFFZlg4RzQ2d3oxMEd2TmQ4TmNiRGEKZjZVSWYxQ0hLVHBBL1dmMlZNVjJDbUtSZDdwQjFvQkVjS1RpakJlbzcvT2VEV282cjh4L25mb1ZtVTVISm1abwpnVmc0WnV1c1B0K3Q5VXhha1BEZkw1UXYrMWtzWGdJcisvYUp2NEFsVkZldTBJUk90YWtJK3NEZitrN2RINmFUCk90czBNaE1DZ1lFQWlZTHNvSDRFZGFJMHBBYkhJRWt6eWE4Ny9PalBidkZjamdzbEdsTmFKTzJqSWpxWGpvT1AKM2tnaTZDT294UDh2VVM1UzdwNG4wSllwc3Z1RHIzM3g2aTVBVWdiOUpVLzYwSkt1clpxb1ZHUHg2dXVQbmdUbgpkSHA0VGVocXBqMlN3MEdveVNoWFZaVFJkcDZYc3NwSlVtdm1YQ29DTitGQkdVWUlQNmUwcWNJPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="

# Use Docker container for faster builds.
sudo: false

python:
  - "2.7"
  - "3.6"

install:
  - pip install pytest
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace
  - python setup.py develop

script:
  - py.test -vv

notifications:
  flowdock: af7fd22c31cc718489c70b625d90b949

cache:
    directories:
        - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
        - /home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages
