language: python

# Use Docker container for faster builds.
sudo: false

python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install .
  - pip install pytest

script:
  - py.test -vv

cache: pip
