language: python

# Use Docker container for faster builds.
sudo: false

python:
  - "3.6"

install:
  - pip install pytest
  - pip install -r requirements.txt
  - pip install .

script:
  - py.test -vv

cache: pip
